### ISSUE TITLE
Crash when attempting to use Arboretum

### ISSUE THREAD

**Issue by blueyu2** [covers1624/LegacyFarms#2]
Putting Humus and Oak Saplings in an Arboretum and powering it results in this crash:

java.lang.NoSuchMethodError: covers1624.lib.util.BlockPosition.getBlock(Lnet/minecraft/world/World;)Lnet/minecraft/block/Block;
	at covers1624.legacyfarms.utils.BlockUtils.shouldBlueprintBreakBlock(BlockUtils.java:122)
	at covers1624.legacyfarms.tile.planter.TilePlanter.clearArea(TilePlanter.java:432)
	at covers1624.legacyfarms.tile.planter.TilePlanter.doWork(TilePlanter.java:403)
	at covers1624.legacyfarms.tile.planter.TilePlanter.func_145845_h(TilePlanter.java:126)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by covers1624** [comment]
Interesting..
looking at it now.

**Comment by covers1624** [comment]
forgot to close this last night, should be fixed, can you confirm?

**Comment by blueyu2** [comment]
It doesn't crash, but the Arboretum isn't placing anything. I have Humus and Oak Saplings in the proper slots, and I am powering it with 1280rf/t from a BuildCraft Creative Engine.
